# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
